FROM maven:3.5-jdk-8 as maven
WORKDIR /usr/src/java-code
COPY . /usr/src/java-code/
RUN mvn package

WORKDIR /usr/src/java-app
RUN cp /usr/src/java-code/target/*.war ./app.war
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]